#!/bin/bash

# THIS FILE IS GENERATED BY AUTOMATION SCRIPT! PLEASE REFER TO ORIGINAL SCRIPT!
# THIS FILE IS MODIFIED AUTOMATICALLY FROM TEMPLATE AND SHOULD BE RUNNABLE!

#SBATCH --partition=gpu_a100_short
#SBATCH --job-name=GRPO_7B_training
#SBATCH --output=GRPO_7B_training.log
#SBATCH --time=00:30:00

### This script works for any number of nodes, Ray will find and manage all resources
#SBATCH --nodes=2
#SBATCH --exclusive

### Give all resources to a single Ray task, ray can manage the resources internally
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-node=4
#SBATCH --cpus-per-task=40
#SBATCH --mem=120G  # 120G per node

# Load modules or your own conda environment here
# module load devel/cuda/12.8 
#module load devel/python/3.11.7-gnu-11.4
# Load Hugging Face token from local file
if [ -f ~/.hf_token ]; then
    export HUGGINGFACE_HUB_TOKEN=$(cat ~/.hf_token)
    export HF_TOKEN=$HUGGINGFACE_HUB_TOKEN
fi

# Load Weights & Biases API key
if [ -f ~/.wandb_token ]; then
    export WANDB_API_KEY=$(cat ~/.wandb_token)
    echo "✅ Wandb API key loaded"
else
    echo "❌ Warning: Wandb token file not found at ~/.wandb_token"
fi

################# DON NOT CHANGE THINGS HERE UNLESS YOU KNOW WHAT YOU ARE DOING ###############
# This script is a modification to the implementation suggest by gregSchwartz18 here:
# https://github.com/ray-project/ray/issues/826#issuecomment-522116599
redis_password=$(uuidgen)
export redis_password

nodes=$(scontrol show hostnames $SLURM_JOB_NODELIST) # Getting the node names
nodes_array=($nodes)

node_1=${nodes_array[0]}
ip=$(srun --nodes=1 --ntasks=1 -w $node_1 hostname --ip-address) # making redis-address

if [[ $ip == *" "* ]]; then
  IFS=' ' read -ra ADDR <<<"$ip"
  if [[ ${#ADDR[0]} > 16 ]]; then
    ip=${ADDR[1]}
  else
    ip=${ADDR[0]}
  fi
  echo "We detect space in ip! You are using IPV6 address. We split the IPV4 address as $ip"
fi

port=6379
ip_head=$ip:$port
export ip_head
echo "IP Head: $ip_head"

echo "STARTING HEAD at $node_1"
# Start head node - let Ray auto-detect resources
srun --nodes=1 --ntasks=1 -w $node_1 \
  ray start --head --node-ip-address=$ip --port=6379 --redis-password=$redis_password --block &
sleep 30

worker_num=$(($SLURM_JOB_NUM_NODES - 1)) #number of nodes other than the head node
for ((i = 1; i <= $worker_num; i++)); do
  node_i=${nodes_array[$i]}
  echo "STARTING WORKER $i at $node_i"
  echo "Worker will connect to: $ip_head"
  
  # Test connectivity first
  echo "Testing connectivity from $node_i to head node..."
  srun --nodes=1 --ntasks=1 -w $node_i ping -c 1 $ip || echo "Ping failed from $node_i"
  
  # Start worker nodes - let Ray auto-detect resources
  echo "Starting Ray worker on $node_i..."
  srun --nodes=1 --ntasks=1 -w $node_i \
    ray start --address $ip_head --redis-password=$redis_password --block &
  
  # Store the PID to check later
  worker_pid=$!
  echo "Worker $i PID: $worker_pid"
  sleep 10
done

# Wait for all workers to join
echo "Waiting for workers to join the cluster..."
sleep 30


bash examples/qwen2_5_vl_7b_geo3k_grpo.sh
